version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest

    steps:
      - checkout

      - run:
          name: Download Arduino packages
          command: ls -l

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop