version: 2

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Download Arduino packages
          command: wget http://downloads.arduino.cc/arduino-1.8.8-linux64.tar.xz && \
                    tar xf arduino-1.8.8-linux64.tar.xz
      - run:
          name: Verify library
          command: $PWD/arduino-1.8.8/arduino --verify --board arduino:avr:uno $PWD/arduino-knock-detector/src/KnockDetector.h

workflows:
  version: 2
  build:
    jobs:
      - build
          filters:
            branches:
              only:
                - develop